<?php include 'includes/header.php';?>
<?php include 'includes/nav.php';?>
<div id="content">
        <h1>About</h1>
    <p>Friendly, non-aggressive, non-dominant, well behaved house dogs welcome! Formerly a puppy raiser for Guide Dogs for the Blind, I am home full time and am a responsible, caring, dog lover with LOTS of dog handling and dog training experience. My home has lots of space and a completely fenced yard. I offer constant companionship, supervision, love, and years of experience raising and training dogs.</p>
    <p>I am a stay at home mom and my husband works out of our home. Both of us are around the house all day. 2 stay at home doggy parents. Other than an occasional meeting or errand, we will spend all day, everyday with your dog. Also our older teens are often around, so there is a house full of dog lovers all ready to lavish your pup with love and attention!</p>
    <p>We have 2 friendly labs, ages 8 and 7. They give our Rover guests plenty of personal space and our home environment is quiet and peaceful - except when the mailman arrives ;) Our pups prefer guest dogs that are non dominant.</p>
    <p>A typical day: up around 7. Out to relieve and then time to eat. Followed by rest or quiet play. Then time to walk. We typically walk 30 to 40 minutes in the morning. Then home to rest, play, nap, chew bones, etc. Excursions to the backyard as desired throughout the day. Sunning on the back deck if the weather cooperates. Late afternoon/early evening is dinner and another walk - another 30 to 40 minutes. Followed by snuggle time, relaxing, bone chewing, etc. Potty breaks are frequent throughout the day - every couple of hours since we are most always at home. Last potty break is around 11pm.</p>
    <p>Experience - everyone in our family is trained to raise and care for puppies for Guide Dogs for the Blind. Together we raised 2 dogs from 8 weeks old to 16 months for this amazing organization, as well as caring for and helping train numerous other puppies for shorter durations. As volunteer puppy raisers we all attended WEEKLY dog training and handling classes for OVER 4 years, so literally hundreds of dog training classes. During this time we took our puppies everywhere we went - movie theaters, restaurants, school, etc. - wearing those cute green "guide puppy in training vests," they were adorable and very well behaved. Among the many dog skills we learned from these years of dog training classes - how to best interact with dogs, how to keep them safe, how to socialize them, and how to teach them basic skills and desired behaviors through positive reenforcement and consistency. Our dog training and handling skills were constantly being evaluated, critiqued, and held to the highest of standards. We are all highly experienced with every aspect of dog care, training, and supervision.</p>
    <p>Second home - we treat our guest dogs just like we treat our own adored pups. Their safety and happiness is our top priority. Our entire family will give your pup lots of love and individual attention and your dog will be part of our family until you return! If you are looking for a home away from home for your cherished pup, that is what we offer!</p>
    <p>Regarding boarding rates - they are for 24 hours of care. If you need additional time, an additional fee will be charged. As soon as you give me drop off and pick up times, I can tell you the exact fee. I try to be flexible with drop offs and pick ups and allow them between 8am and 10pm.</p>
    <p>When my schedule allows, I am happy to do a dog walk or a drop in visit or daycare. Walks or drop in visits are only for pups who live near me in Madrona.</p>
    <h4>Why I love dog sitting</h4>
    <p>I love the extra energy, sweetness, and the love that each dog contributes to our home! I love getting to know each new dog and having the chance to bond with them and to make new friends. Before joining Rover, over 2 years ago, we were already dog sitting for our friends and neighbors. We are those people. With our love for dogs combined with our dog handling skills and knowledge, we can't imagine not dog sitting!</p>
    <h4>About my yard</h4>
    <p>We are on a double lot - 6000 square feet. Our yard is completely fenced - fence height varies - low end is 39" and high end is 6 feet. We do not leave dogs unsupervised in the yard, ever. Many of the photos on my profile show the dogs playing, sunning, or running in our backyard - we have grass, paved patio, wood deck, shade areas, sun areas, and lots of places to explore and sniff. Our yard is like a private doggy paradise, perfect for both play and relaxation and the dogs have access to it all day, as frequently as they like, under my watchful eye.</p>
    <h4>My experience administering medication:</h4>
    <p>I have given pills and administered ear drops.</p>
        <blockquote>
            <p><strong>"</strong>Kandice is the best. She adores the dogs and walks them multiple times a day and takes pictures to help us with our separation anxiety. If you are lucky enough, you should engage Kandice to love on your pups while you're away.<strong>"</strong></p>
            <h4>David and Patrick</h4>
        </blockquote>
<?php include 'includes/cta.php';?>
<?php include 'includes/footer.php';?>